### ISSUE TITLE
Gke helm example has no example

### ISSUE THREAD

**Issue by ed-cloudmatos** [gruntwork-io/terraform-google-gke#102]
https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-basic-helm

There is a readme, no actual code.

**Comment by robmorgan** [comment]
Hi @ed-cloudmatos, admittedly we can make it more clear, but the [root of this repo has an example for using Helm](https://github.com/gruntwork-io/terraform-google-gke#quickstart). I'll leave this issue open until we update the READMEs with further clarity.

**Comment by ed-cloudmatos** [comment]
Can you show me where?
This looks like the path, there is nothing there example wise.

https://github.com/gruntwork-io/terraform-google-gke/tree/master/examples/gke-basic-helm

**Comment by robmorgan** [comment]
Hi @ed-cloudmatos, look at the Terraform files in the root of the repo: https://github.com/gruntwork-io/terraform-google-gke

**Comment by boldandbusted** [comment]
@ed-cloudmatos Howdy. So, you literally need to look at the *root* of the repo - aka the top level of the repo, for the files ending in .tf. :) NOT in the folder named 'root' that has the README. They have to do it this way so that they can have a README that represents the entire repo at the top level, and then in `<repo>/root/` have a README that documents the example that's in  `<repo>/`. Check out the `main.tf`, `variables.tf`, etc. in the top-level directory in this repo. Those are the examples you seek. :) It *is* confusing, but a common pattern with Gruntwork's modules. It makes sense once you get used to it. Hope this helps. Cheers.

**Comment by eak12913** [comment]
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)
