### ISSUE TITLE
Helm example has no files besides Readme

### ISSUE THREAD

**Issue by nodiex-admin** [gruntwork-io/terraform-google-gke#93]
The master branch helm example doesn't have anything. 

Do all operations of creating a cluster initialize helm correctly as specified in the Google Cloud post?

**Comment by yorinasub17** [comment]
The helm example is the terraform code in the root folder of the repo. We have to do it this way because of a requirement with the Hashicorp terraform module registry to have terraform code at the root.

Note that the `master` branch has moved on from the blog post and is using Helm 3. In Helm 3, there is no server side component of Helm, so a base GKE cluster is all you need to start using Helm. The example shows you how you can string together the dependencies so that you can invoke the `helm` provider in the same terraform file as deploying a new GKE cluster.

Hope this helps!

**Comment by robmorgan** [comment]
Hi @nodiex-admin,

If you want to use the legacy GKE Helm 2 example that is referenced in the Google Cloud post, then you can simply use an older tag, e.g: https://github.com/gruntwork-io/terraform-google-gke/tree/v0.4.3

**Comment by robmorgan** [comment]
I'll leave this issue open for now, but close it if I haven't heard back from you in a week.
